quarkus.log.level=INFO
quarkus.log.category."hr.ja".level=DEBUG
# exclude META-INF/resources from the build

#quarkus.qute.exclude-patterns=**/*.js,**/*.css,**/*.map
#quarkus.qute.extensions=qute.html
#quarkus.http.static-resources.locations=static,META-INF/resources
#quarkus.qute.template-path-exclude=static/.*\.js,^\.DS_Store$
quarkus.qute.extensions=html
#quarkus.qute.exclude-patterns=**/*.js,**/*.css,**/*.map,**/*.json
#quarkus.http.static-resources.locations=webapp